spring.application.name=identidad
server.port=${SERVER_PORT:8080}
#spring.config.import=optional:file:.env[.properties]

# TODO: definir variables de entorno en producción (DB_URL, DB_USER, DB_PASSWORD, JWT_SECRET)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/identidad?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
# solo desarrollo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secreto=${JWT_SECRET:dev-secret-change-me-32-bytes-minimum}
jwt.expiracion=${JWT_EXPIRATION:86400000}
