spring.application.name=gestionacademica_microservice

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

spring.config.import=optional:file:.env[.properties],optional:file:gestionacademica/.env[.properties]

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/gestionacademica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

server.port=${SERVER_PORT:8087}

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.api-docs.enabled=true

# URL MS0 Identidad - puerto a puerto
# En Docker usar variable: IDENTIDAD_URL=http://identidad:8080
identidad.url=${IDENTIDAD_URL:http://localhost:8080}

# URL MS9 Academica - puerto a puerto
# En Docker usar variable: MS_ACADEMICA_URL=http://academica:8083
microservices.academica.url=${MS_ACADEMICA_URL:http://localhost:8083}
