### Variables
@ms5 = http://localhost:8089

### Enviar mensaje directo
POST {{ms5}}/api/mensajeria/enviar
Content-Type: application/json

{
  "runEmisor": "12345678-5",
  "asunto": "Reunion de apoderados",
  "contenido": "Se convoca a reunion el viernes a las 19:00",
  "runReceptor": "22222222-2"
}

###
### Enviar mensaje masivo
POST {{ms5}}/api/mensajeria/masivo
Content-Type: application/json

{
  "runEmisor": "12345678-5",
  "asunto": "Comunicado general",
  "contenido": "Se informa a toda la comunidad escolar..."
}

###
### Responder mensaje recibido
POST {{ms5}}/api/mensajeria/responder/1
Content-Type: application/json

{
  "runEmisor": "22222222-2",
  "asunto": "Re: Reunion de apoderados",
  "contenido": "Confirmo asistencia",
  "runReceptor": "12345678-5"
}

###
### Ver mensajes recibidos por usuario
GET {{ms5}}/api/mensajeria/recibidos?runUsuario=22222222-2

###
### Ver mensajes enviados por usuario
GET {{ms5}}/api/mensajeria/enviados?runUsuario=12345678-5
