spring.application.name=notas
server.port=${SERVER_PORT:8090}
spring.config.import=optional:file:.env[.properties],optional:file:notas/.env[.properties]

# Configuracion por entorno (local por defecto)
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/notas?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# URL MS0 Identidad
# TODO-PUERTO-MS0: cambiar cuando se definan puertos finales
identidad.url=${IDENTIDAD_URL:http://localhost:8080}

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.api-docs.enabled=true

# URL MS7 Gesti?n Acad?mica - puerto a puerto
# En Docker usar variable: GESTION_ACADEMICA_URL=http://gestionacademica:8087
gestionacademica.url=${GESTION_ACADEMICA_URL:http://localhost:8087}

# URL MS3 Matr?cula - puerto a puerto
# En Docker usar variable: MATRICULA_URL=http://matricula:8088
matricula.url=${MATRICULA_URL:http://localhost:8088}
