# Puerto MS5 Mensajería
# TODO-PUERTO-MS5: cambiar cuando se definan puertos finales
server.port=${SERVER_PORT:8081}
spring.config.import=optional:file:.env[.properties],optional:file:mensajeria/.env[.properties]

spring.application.name=mensajeria

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mensajeria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:mensajeria}
spring.datasource.password=${DB_PASSWORD:Atlantis@_1425}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Secreto compartido con MS0 Identidad para validar JWT
jwt.secreto=${JWT_SECRET:}

# TODO: show-sql=false en producción
