# Puerto MS5 Mensajeria
# TODO-PUERTO-MS5: cambiar cuando se definan puertos finales
server.port=${SERVER_PORT:8089}
spring.config.import=optional:file:.env[.properties],optional:file:mensajeria/.env[.properties]

spring.application.name=mensajeria
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/mensajeria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# TODO: show-sql=false en produccion
