spring.application.name=geografia_microservice

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

spring.config.import=optional:file:.env[.properties],optional:file:geografia/.env[.properties]

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/geografia?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
server.port=${SERVER_PORT:8086}

springdoc.swagger-ui.path=/geografia.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operations-sorter=alpha
springdoc.api-docs.enabled=true

spring.sql.init.mode=always

